import type { Metadata } from "next";
import AuthProvider from "@/context/AuthProvider";
import Header from "@/components/header/Header";
import { CssBaseline } from "@mui/material";

export const metadata: Metadata = {
  title: "Datasoft - Data Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <CssBaseline />
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
